"""Add support contacts, coping activities, red zone logs

Revision ID: 105e2f0e4f79
Revises: 7bf0f9eb3eb6
Create Date: 2025-07-21 16:41:52.376249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105e2f0e4f79'
down_revision = '7bf0f9eb3eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_coping_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('mood_tag', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_support_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('relationship', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('preferred_channel', sa.String(length=20), nullable=True),
    sa.Column('ok_to_notify', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_red_zone_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('did_contact', sa.Boolean(), nullable=True),
    sa.Column('did_activity', sa.Boolean(), nullable=True),
    sa.Column('did_grounding', sa.Boolean(), nullable=True),
    sa.Column('escalation_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_red_zone_logs')
    op.drop_table('user_support_contacts')
    op.drop_table('user_coping_activities')
    # ### end Alembic commands ###
