"""Make user_session_number non-nullable

Revision ID: 7bf0f9eb3eb6
Revises: ab45de5a6e26
Create Date: 2025-07-20 22:10:09.313347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf0f9eb3eb6'
down_revision = 'ab45de5a6e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_threads', schema=None) as batch_op:
        batch_op.alter_column('user_thread_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('user_session_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('user_session_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('journal_threads', schema=None) as batch_op:
        batch_op.alter_column('user_thread_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
