"""Add thread and role for two-way journaling

Revision ID: 96a4006eee20
Revises: fe7a7c0d8537
Create Date: 2025-07-13 14:39:51.113216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a4006eee20'
down_revision = 'fe7a7c0d8537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=True))
        batch_op.create_foreign_key(None, 'journal_threads', ['thread_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role')
        batch_op.drop_column('thread_id')

    op.drop_table('journal_threads')
    # ### end Alembic commands ###
