"""Add ok_to_notify to User

Revision ID: a3f9780a5845
Revises: 105e2f0e4f79
Create Date: 2025-07-21 19:37:22.688639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3f9780a5845'
down_revision = '105e2f0e4f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_thread_id'), ['thread_id'], unique=False)

    with op.batch_alter_table('journal_threads', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_journal_threads_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_threads_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_coping_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_coping_activities_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_coping_label', ['user_id', 'label'])

    with op.batch_alter_table('user_red_zone_logs', schema=None) as batch_op:
        batch_op.alter_column('triggered_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_user_red_zone_logs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_red_zone_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_support_contacts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_user_support_contacts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_support_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_support_contacts_user_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('user_red_zone_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_red_zone_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_red_zone_logs_session_id'))
        batch_op.alter_column('triggered_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('user_coping_activities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_coping_label', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_coping_activities_user_id'))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.alter_column('start_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('journal_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_threads_user_id'))
        batch_op.drop_index(batch_op.f('ix_journal_threads_session_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_thread_id'))

    # ### end Alembic commands ###
