"""Add user_session_number and user_thread_number

Revision ID: ab45de5a6e26
Revises: aba1391fac71
Create Date: 2025-07-16 22:06:29.334953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab45de5a6e26'
down_revision = 'aba1391fac71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('journal_threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_thread_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_session_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('user_session_number')

    with op.batch_alter_table('journal_threads', schema=None) as batch_op:
        batch_op.drop_column('user_thread_number')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###
