"""Add dominant_emotion and top_emotions to Session

Revision ID: aba1391fac71
Revises: e8af235b0033
Create Date: 2025-07-15 17:39:17.379598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aba1391fac71'
down_revision = 'e8af235b0033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sessions', ['session_id'], ['id'])

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dominant_emotion', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('top_emotions', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('top_emotions')
        batch_op.drop_column('dominant_emotion')

    with op.batch_alter_table('journal_threads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
